### ISSUE TITLE
Warnings about locale from dev-c7

### ISSUE THREAD

**Issue by aawdls** [epics-containers/k8s-epics-utils#4]
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8): No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
```

**Comment by gilesknap** [comment]
In ubuntu this can be fixed with 
`apt install locale`

I have yet to work out how to do it on centos (And have spent a bit of time trying)

**Comment by aawdls** [comment]
If you 
`unset LC_ALL`
Then the messages go away. However I'm not sure what the side effects of this would be.

**Comment by aawdls** [comment]
Another approach to preserve the en_GB setting. I was able to make it work by adding the following lines to the build
```
RUN sed -i "s/override_install_langs=en_US/override_install_langs=en_GB/" /etc/yum.conf
ENV LC_ALL=en_GB.utf8
RUN yum reinstall -y glibc-common
```
This is based on  https://stackoverflow.com/questions/52401710/change-system-locale-inside-a-centos-rhel-without-using-localectl and other results from furious googling.
Not sure why the inconsitency in the capitalisation of "utf8" requiring me to change the env var.

Any thoughts on these approaches?

**Comment by gilesknap** [comment]
Andy, I have also seen the yum reinstall approach and think that is the way to go.

**Comment by aawdls** [comment]
I found that I have `LC_ALL` set in my .bashrc_local.

It does not seem to be required for me elsewhere any more. So as long as nobody else is getting this issue then I think we can take no further action on the Dockerfile. If it does come up again then I think the glibc-common change above will work.

**Comment by gilesknap** [comment]
@aawdls I'm not sure this is resolved. Michael Abbott has seen this and it is because some apps he wants to use are trying to set locale.
